### ISSUE TITLE
Game Crashing When encountering Mooblooms on Server hosted by Essential 2.0.9

### ISSUE THREAD

**Issue by LooseTongue1** [Faboslav/friends-and-foes#201] opened 2024-03-12 03:02 UTC
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.2.20 (Forge)

### Mod version information

2.0.9

### Reproduction Steps

1. Create a gamemode creative server using the Essential mod.
2. Spawn mooblooms.
3. Invite players to the server.
4. All invited players except for the host crashed due to entity unable to be rendered.

### Crash Report and latest.log

[message.txt](https://github.com/Faboslav/friends-and-foes/files/14566579/message.txt)

**Comment by Faboslav** [comment] 2024-03-12 06:57
Duplicate of https://github.com/Faboslav/friends-and-foes/issues/187 and https://github.com/Faboslav/friends-and-foes/issues/179, nothing i can do about this.

**Comment by Faboslav** [comment] 2024-03-13 17:36
This is pretty unclear, but i will try to implement some kind of "fallback" so this does not happen even when the bug is probably not caused by Friends&Foes.

**Comment by Faboslav** [comment] 2024-03-15 13:13
Should be fixed with 2.0.10 version.

**Closed by Faboslav** 2024-03-15 13:13 UTC
Labels: Possible Bug
