### ISSUE TITLE
[1.20.1 Fabric] Too many Maulers spawning?

### ISSUE THREAD

**Issue by pewblaze** [Faboslav/friends-and-foes#126] opened 2023-07-12 18:44 UTC
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.14.21

### Mod version information

friendsandfoes-fabric-mc1.20.1-1.9.3.jar

### Expected Behavior

I guess lesser mauler?

### Actual Behavior

Too many maulers are spawning (after world generation, didnt play at all)

### Reproduction Steps

1. Create World
2. Join
3. Find Maulers 

### Screenshots & files

![grafik](https://github.com/Faboslav/friends-and-foes/assets/96242065/d4af1bd3-ecf2-44bd-8ddb-b108d48135fc)

Log:
https://gist.github.com/pewblaze/63fe0a873e3c38551df1413a6eb5af34

**Comment by Faboslav** [comment] 2023-07-12 19:33
You are just around the biomes, where maulers are almost only creature/animal which can spawn. As they count in as animals, there is nothing i can do to limit the spawns.

**Comment by pewblaze** [comment] 2023-07-12 20:09
Thats bad :( There are A LOT 
![grafik](https://github.com/Faboslav/friends-and-foes/assets/96242065/37585a7f-91da-4361-9eba-88eb16e15de5)

**Comment by Faboslav** [comment] 2023-07-14 05:45
Creature spawn cap is exactly 10, this is very unusual then, could there be another mod messing with the spawn caps/rates?

**Comment by pewblaze** [comment] 2023-07-14 06:40
Not that i know, but i will watch out for it. Maybe i find the cause. :)

**Comment by mateus3c** [comment] 2023-08-09 20:59
> Creature spawn cap is exactly 10, this is very unusual then, could there be another mod messing with the spawn caps/rates?

Im having the exactly same problem, there is literally thousands of maulers spawning on my world

**Comment by Faboslav** [comment] 2023-08-10 13:22
Hmm, can you post your modlist please? Also I dont know, how to debug this :/ with that many mods

**Comment by mateus3c** [comment] 2023-08-11 03:38
> I've had the same issue recently too. I believe it has something to do with the Respawning Animals mod(found in your mod list from your log), as adding the mauler to its blacklist seemed to heavily reduce the issue(after using commands to remove literally 3k maulers).
> 
> Would probably need some testing to confirm or deny if it has something to do with Respawning Animals, but hopefully this helps.

That actually makes sense! I have the Respawning Animals mod installed too!

**Comment by Faboslav** [comment] 2023-08-13 09:45
I will try to reproduce the issue with mentioned mod, and based on that i will create issue or not, we will see :).

**Comment by Faboslav** [comment] 2023-08-13 13:58
I tried, to fly around the desert with respawning animals mod, killed like 171 maulers, so i am not sure the Respawning Animals is the cause :/.

**Comment by Superkat32** [comment] 2023-08-13 15:35
> I tried, to fly around the desert with respawning animals mod, killed like 171 maulers, so i am not sure the Respawning Animals is the cause :/.

How long did you stick around in the area waiting for maulers to spawn? I know that it was only an issue for me after hanging out in the same area for a while(don't remember exactly how long, happened almost 2 weeks ago now).

I'm going to do some of my own testing to make sure I don't accidentally use up your time incase my theory is wrong. I'll be testing hanging out in the same area for some time with and without the respawning animals mod. I'll comment my results in a once I have them.

**Comment by Superkat32** [comment] 2023-08-13 16:20
My results.

**10 minutes with Respawning Animals:**
Around 730 maulers spawned.

**10 minutes without Respawning Animals:**
Around 3 maulers spawned... Flying around in different parts of the desert had anywhere from 3 to 20-ish maulers spawn initially, but never really increasing.

**Important info:**
- I didn't move all that much for either test. I was pretty much afk.
- I was in the same spot for both tests(doing the test with Respawning Animals first)
- Render distance was 12
- Sim. distance was 5
- Entity distance was 100%
- Minecraft version 1.20.1
- Friends and Foes version `fabric-mc1.20.1-1.9.3`
- Respawning Animals version `v8.0.0-1.20.1-Fabric`
- I was in the middle of the desert right next to a mesa in the spawn chunks(I got a lucky spawn, lol)
- It was day time for both tests.

**Other mods loaded:**
Fabric API
Mod Menu
Puzzles Lib
Forge Config API Port

**Possible Solution**
I'm still pretty sure this has something to do with Respawning Animals. It seems like both mods are doing what they should be doing. Friends and Foes is spawning maulers initally, and Respawning Animals is letting the maulers keep spawning. However, something seems to be preventing the maulers from despawning. Flying around with both mods causes what you'd expect without Respawning Animals, a normal amount of maulers. But staying in place allows Respawning Animals to spawn in more maulers. That's what I think is going on.

It seems like in Respawning Animals' [config](https://github.com/Fuzss/respawninganimals/blob/e2d7724313da735a79bf5e97fa3622d48b422e7b/1.20/Common/src/main/java/fuzs/respawninganimals/config/ServerConfig.java#L14C39-L14C86), there is already one mob from another mod which is automatically blacklisted. I wonder if you could create a PR to add maulers to that pre-determined list for a temporary solution?

**Comment by Faboslav** [comment] 2023-08-13 18:17
@Superkat32
I must say, that this is just wonderful and very helpful, I will try to do the testing the same way, but it is almost certain, that this is issue is related to Respawning Animals, I will try to do it your way again and based on that create PR for blacklisting Maulers.

Before this, I tried to stick to small area with high simulation distance and got around 170 maulers, so not anything extreme.

Thank you for this collaboration!

**Comment by Superkat32** [comment] 2023-08-13 20:08
Glad I could be of help!

On that note, I wanted to mention that I love Friends and Foes! I just love the copper golems and the mooblooms and how they work in-game! Keep up the fantastic work!

**Comment by Faboslav** [comment] 2023-08-14 14:30
Author of Respawning Animals said, that he is aware of this issue and will do some global fix. So i will close this for now. It is always nice to see when people do enjoy my mod, so thank you :).

**Closed by Faboslav** 2023-08-14 14:30 UTC
