### ISSUE TITLE
[Question] Beekeeper

### ISSUE THREAD

**Issue by Looodon** [Faboslav/friends-and-foes#74] opened 2022-11-05 03:19 UTC
Minecraft version information
1.19.2

Hey,
I changed the config options to:
  "enableBeekeeperVillagerProfession": false,
  "generateBeekeeperAreaStructure": false
but the villager is still getting the beekeeper profession. Is there another way to stop the villager from getting the profession or disabling the trade through a datapack? (if so what would I replace the code with?)
Thank you! :)

**Comment by Faboslav** [comment] 2022-11-05 09:04
Hello, if this is not working as intended i would like to try fix it :).

So when `generateBeekeeperAreaStructure` is `false`, no beekeeper structure should generate in any of the villages.
When `enableBeekeeperVillagerProfession` is `false` all already existing beekepers will still exist, but when you place any beehive and a villager, he should not allocate the profession.

Can you please test these two situations and confirm on that(or not)? Based on that i will try make some changes.

**Comment by Faboslav** [comment] 2022-11-05 09:42
Thank you, i will try to debug it, and hopefully fix it, about the datapack question i think it is not possible to disable trades and/or profession like that.

**Comment by Faboslav** [comment] 2022-11-05 10:24
I think i fixed it and even improved it, so even existing beekeepers will transform into the normal villagers, fix will be released with the next update, which is 1.6.0 hopefully soon :).

**Comment by Faboslav** [comment] 2022-11-05 10:56
I know, that there is one mod, allowing to define trades via json, thus datapacks, but mojang is not there yet(or at least i dont know about it)

**Comment by Faboslav** [comment] 2022-11-19 19:12
Fix will be released this weekend with 1.6.0 version.

**Closed by Faboslav** 2022-11-19 19:12 UTC
Labels: Confirmed Bug
