### ISSUE TITLE
Many Glares everywhere

### ISSUE THREAD

**Issue by VoidLock92** [Faboslav/friends-and-foes#16] opened 2022-02-03 21:20 UTC
### Minecraft version information

1.18.1

### Mod version information

friendsandfoes-mc1.18.1-1.2.2

### Expected Behavior

Not have so many mobs

### Actual Behavior

Way to many mobs

### Reproduction Steps

A player was exploring caves and realized these spawn way to often, something must be wrong to have this many. This was not noticed in previous version so might have been introduced recently.

### Screenshots & files

![image](https://user-images.githubusercontent.com/21327041/152430514-7b6b257e-0522-4224-9f15-acd039d5dbec.png)

**Comment by Faboslav** [comment] 2022-02-04 06:38
Hello, Glare is persistent now, so that is probably the reason.I will change that only tamed or named glares are persistent. This fix will be released probably tomorow along with few other fixes.

**Comment by Faboslav** [comment] 2022-02-05 11:09
So new version is available, let me please know if the issue is resolved:
https://github.com/Faboslav/friends-and-foes/releases/tag/mc1.18.1-1.2.3
https://www.curseforge.com/minecraft/mc-mods/friends-and-foes/files/3637344

**Closed** 2022-02-05 11:13 UTC
Labels: bug
