### ISSUE TITLE
Better Illager Iceologer Texture 

### ISSUE THREAD

**Issue by QwertRvg** [Faboslav/friends-and-foes#280] opened 2024-10-18 19:06 UTC
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

0.16.5

### Mod version information

3.0.3

### Expected Behavior

For the Iceologer to look normal / as intended.

### Actual Behavior

The Iceologer looks very very weird when the Better Illagers resource pack is used. Because the Iceologer borrows visuals from another Illager, I think.

### Reproduction Steps

1. Download Friends and Foes
2. Download and use Better Illagers
3. Spawn an Iceologer
4. look at it

### Screenshots & files

![image](https://github.com/user-attachments/assets/5d336a21-4772-4d5b-84c5-4242d8edeef6)

**Comment by Faboslav** [comment] 2024-10-20 07:06
Duplicate of https://github.com/Faboslav/friends-and-foes/issues/281

**Closed by Faboslav** 2024-10-20 07:06 UTC
