### ISSUE TITLE
Moobloom crashes Players when connected to a Essential Server

### ISSUE THREAD

**Issue by RiskE80** [Faboslav/friends-and-foes#187] opened 2024-01-10 05:32 UTC
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.2.19

### Mod version information

2.0.7

### Reproduction Steps

1. Host Essential World
2. Invite friend
3. Spawn Moobloom

### Crash Report and latest.log

[crash-2024-01-09_21.26.40-client.txt](https://github.com/Faboslav/friends-and-foes/files/13883437/crash-2024-01-09_21.26.40-client.txt)

[latest.log](https://github.com/Faboslav/friends-and-foes/files/13883442/latest.log)

### Additional information

the crash happens whenever a player that isnt the host attempts to render in a Moobloom essential may or may be a factor in this since it only crashes the game for the joined players instead of the host

**Comment by Faboslav** [comment] 2024-01-12 08:39
Hello this is a duplicate of https://github.com/Faboslav/friends-and-foes/issues/187, watch the mentioned issue for the possible future fixes please.

**Closed by Faboslav** 2024-01-12 08:39 UTC
