### ISSUE TITLE
Entity error on server

### ISSUE THREAD

**Issue by katubug** [Faboslav/friends-and-foes#171] opened 2023-12-14 17:41 UTC
### Minecraft version information

1.20.1

### Mod loader information

Forge

### Mod loader version information

47.2.17

### Mod version information

2.0.4

### Expected Behavior

unsure

### Actual Behavior

Found the following in my logs:

```[14Dec2023 12:04:17.674] [Server thread/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/multiplayer/PlayerInfo for invalid dist DEDICATED_SERVER
[14Dec2023 12:04:17.674] [Server thread/ERROR] [ModernFix/]: Skipping entity ID sync for com.faboslav.friendsandfoes.entity.PlayerIllusionEntity: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/PlayerInfo for invalid dist DEDICATED_SERVER
```

### Reproduction Steps

Unsure.

Sorry for not using the template properly. I'm having some issues where my server hangs or restarts randomly and I'm troubleshooting, so I'm combing my log files. I don't think your mod is the cause of this issue, but I did get the above lines in my log and thought you might like to know about it.

**Comment by Faboslav** [comment] 2023-12-14 17:42
Hello there, thanks you for the report, also yeah as you said, i dont think this is the cause of your crashs/hangs, but i will try to look at this some time later.

**Comment by katubug** [comment] 2023-12-14 18:28
Thank you!

**Comment by Faboslav** [comment] 2023-12-17 08:12
So i looked into this(that error/warning) and i cant find anything related, will close this right now, in case that this somehow causes crash in the game, please do let me know.

**Closed by Faboslav** 2023-12-17 08:12 UTC
