### ISSUE TITLE
[Crash] Game and servers both crash when using F&F with Chipped mod pumpkins on armor stands

### ISSUE THREAD

**Issue by gamerpotion** [Faboslav/friends-and-foes#125] opened 2023-07-11 15:42 UTC
### Minecraft version information

1.20.1

### Mod loader information

Fabric

### Mod loader version information

Fabric 0.14.21

### Mod version information

friendsandfoes-fabric-mc1.20.1-1.9.2.jar

### Reproduction Steps

Install the mods as seen in below screenshot.

In game, put an armor stand, then put a pumpkin from the Chipped mod on the armor stand and see it unfold

<img src="https://media.discordapp.net/attachments/1003407908463190073/1128349228683513926/image.png" />

### Crash Report and latest.log

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-07-11 16:36:24
Description: Exception in server tick loop

java.lang.AbstractMethodError: Receiver class net.minecraft.class_2276 does not define or inherit an implementation of the resolved method 'abstract net.minecraft.class_1304 method_7685()' of interface net.minecraft.class_5151.
	at net.minecraft.class_1309.method_32326(class_1309.java:3463)
	at net.minecraft.class_1531.method_5664(class_1531.java:327)
	at net.minecraft.class_3244$1.method_33898(class_3244.java:1594)
	at net.minecraft.class_3244$1.method_33897(class_3244.java:1578)
	at net.minecraft.class_3244$1.method_34220(class_3244.java:1594)
	at net.minecraft.class_2824$class_5910.method_34213(class_2824.java:146)
	at net.minecraft.class_2824.method_34209(class_2824.java:66)
	at net.minecraft.class_3244.method_12062(class_3244.java:1571)
	at net.minecraft.class_2824.method_12251(class_2824.java:53)
	at net.minecraft.class_2824.method_11054(class_2824.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1061494912 bytes (1012 MiB) / 2474639360 bytes (2360 MiB) up to 6710886400 bytes (6400 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3598
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23505.60
	Virtual memory used (MB): 20627.45
	Swap memory total (MB): 7196.02
	Swap memory used (MB): 973.93
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6400m -Xms256m
	Fabric Mods: 
		athena: Athena 3.0.0
		chipped: Chipped 3.0.1
		fabric-api: Fabric API 0.85.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.8+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.12+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.8+40e50c4677
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.38+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.42+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.48+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.0+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.8+e3d6ed2577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.3+43a3fedd77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabricloader: Fabric Loader 0.14.21
		friendsandfoes: Friends&Foes 1.9.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		resourcefullib: Resourceful Lib 2.1.1
			com_teamresourceful_yabn: yabn 1.0.3
	Server Running: true
	Player Count: 1 / 8; [class_3222['GamerPotion'/178, l='ServerLevel[New World]', x=-0.38, y=128.00, z=3.31]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.21-1.20.1

**Comment by Faboslav** [comment] 2023-07-11 15:57
How is this based on the log related to this mod? Based on this i am not sure what to fix

**Comment by gamerpotion** [comment] 2023-07-11 16:06
> How is this based on the log related to this mod? Based on this i am not sure what to fix, will try to do this in-game anyway then.

yeah sorry I dont know what is causing it, but just installing F&F and Chipped mod (and no other mods) on latest fabric, it crashes.

also for some reason F&F allows armor stand to equip pumpkins?  maybe disable that feature and it will go away

**Comment by ThatGravyBoat** [comment] 2023-07-11 16:21
The problem is that in this mixin https://github.com/Faboslav/friends-and-foes/blob/master/common/src/main/java/com/faboslav/friendsandfoes/mixin/CarvedPumpkinBlockMixin.java you implement equipment but that is not valid as CarvedPumpkinBlock is not equipable only EquipableCarvedPumpkinBlock is.

**Comment by ThatGravyBoat** [comment] 2023-07-11 16:22
this bug would also be present in vanilla with a jack-o-lantern

**Comment by Faboslav** [comment] 2023-07-11 16:29
This is not a problem, original class is defined like this:
`public class CarvedPumpkinBlock extends HorizontalFacingBlock implements Wearable {`

**Comment by ThatGravyBoat** [comment] 2023-07-11 16:34
in 1.20 that changed, CarvedPumpkinBlock is now used for both Jack-O-Lanterns and Carved Pumpkins, in 1.20 Wearable was removed and Equipable was added which in 1.20 EquipableCarvedPumpkinBlock was added to implement Equipable, what is happening in your mixin is that you are implementing Equipable which means that it adds that implements to the bytecode which then makes it so the JVM expects all CarvedPumpkinBlock to implement the getEquipmentSlot method which does not exist on normal CarvedPumpkinBlock only EquipableCarvedPumpkinBlock

**Comment by Faboslav** [comment] 2023-07-11 16:35
Oh sorry, i looked at 1.19.2, will try to look at this then asap

**Comment by Faboslav** [comment] 2023-07-11 16:40
I think removing that interface should be enough right?

**Comment by ThatGravyBoat** [comment] 2023-07-11 20:52
Yes removing that implementation should fix the error idk if that changes your mixin or intended use though.

**Comment by Faboslav** [comment] 2023-07-12 11:51
Should be fixed with latest release, let me know :).

**Closed** 2023-07-17 08:12 UTC

**Comment by gamerpotion** [comment] 2023-07-21 01:56
all good :)
