### ISSUE TITLE
Flower Mooblom mod crash with new update 5th december

### ISSUE THREAD

**Issue by YeronsOnDreams** [Faboslav/friends-and-foes#167] opened 2023-12-05 19:52 UTC
### Minecraft version information

1.19.2

### Mod loader information

Fabric

### Mod loader version information

0.15.0 (Fabric)

### Mod version information

fabric-mc1.19.2-2.0.2

### Reproduction Steps

I got this error when i updated the mod to the 5th december version to 1.19.2 fabric

### Crash Report and latest.log

![image](https://github.com/Faboslav/friends-and-foes/assets/153021713/2d51f8cc-e13a-4e46-9654-a2465425b952)

**Comment by Neo-Qwerty** [comment] 2023-12-05 20:56
Also had that crashing error!
[crash-2023-12-05_15.44.14-client.txt](https://github.com/Faboslav/friends-and-foes/files/13572802/crash-2023-12-05_15.44.14-client.txt)

Minecraft 1.20.1, Fabric Loader 0.15.0
Friends & Foes 2.0.2, Flowery Mooshrooms 1.1.0.

The culprit is the presence of Flowery Mooshrooms with this version of Friends & Foes, removing Flowery Mooshrooms stops the crash.

**Comment by Faboslav** [comment] 2023-12-05 20:57
Hello, for now rollback friends&foes or disable flowery mooblooms, I will try to release a new version of flowery mooblooms tomorrow

**Comment by Faboslav** [comment] 2023-12-05 20:57
For context, this is caused due to the change, that the moobloom variants are now datapack driven.

**Comment by SaraXianLin** [comment] 2023-12-06 04:24
I have the same issue
[latest.log](https://github.com/Faboslav/friends-and-foes/files/13575824/latest.log)

**Comment by Faboslav** [comment] 2023-12-06 10:02
Should be fixed with the new 2.0.0 release.

**Closed by Faboslav** 2023-12-06 10:02 UTC

**Comment by A5ho9999** [comment] 2023-12-06 10:28
Confirmed fixed for me, thank you
